# Site wide configuration

title: ENEE351
sub-title: Algorithms and Data Structures  
semester: Spring 2020
description: Algorithms and Data Structures
locale:
url: //enee351.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
